name: Bug Report
description: Report a bug in the project
title: "fix(<context>): <msg>"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide the details below. After submission, a workflow will automatically update the issue title based on your inputs.

  - type: dropdown
    id: context
    attributes:
      label: Context
      description: Select the relevant context for the bug.
      options:
        - builder
        - ci/cd
        - engine core
        - engine maths
        - engine physics
        - engine renderer
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a short summary message for the bug (this will be used in the title).
      placeholder: e.g., Fixed rendering glitch in shadows
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the bug.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
