name: "Feature Request"
description: Suggest a new feature or improvement
title: "TEMPORARY TITLE"
labels: ["enhancement"]

body:
  - type: dropdown
    id: issue_type
    attributes:
      label: Type
      description: Confirm the type of report
      options:
        - Feature
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion! Please provide the details below. After submission, a workflow will automatically update the issue title.

  - type: dropdown
    id: context
    attributes:
      label: Context
      description: Select the relevant context for the feature.
      options:
        - builder
        - ci/cd
        - engine core
        - engine maths
        - engine physics
        - engine renderer
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a short summary message for the feature.
      placeholder: e.g., Support for real-time raytracing
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your idea and why it would be useful.
      placeholder: I would like to see...
    validations:
      required: false
