name: Feedback / Report
description: Report a bug or suggest a new feature
title: "TEMPORARY TITLE"
labels: ["bug"]

body:
  - type: dropdown
    id: issue_type
    attributes:
      label: Type
      description: Bug or Feature?
      options:
        - Bug
        - Feature
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide the details below. After submission, a workflow will automatically update the issue title based on your inputs.

  - type: dropdown
    id: context
    attributes:
      label: Context
      description: Select the relevant context for the bug.
      options:
        - builder
        - ci/cd
        - engine core
        - engine maths
        - engine physics
        - engine renderer
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a short summary message for the bug.
      placeholder: e.g., Fixed rendering glitch in shadows
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe how to reproduce the bug.
      placeholder: |
        1. While doing '...'
        2. This happens '...'
        3. See the error
      validations:
        required: false
      if: "issue_type == 'Bug'"
